# Generated by Django 4.2.14 on 2024-07-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='access',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
